### ISSUE TITLE
Access denied 

### ISSUE THREAD

**Issue by Felix-Jonathan** [fhebuterne/MarketPlace#22]
### Bug Description

Hello Guy !

I'm not a good dev so I need your help...
Without configuration file (First Installation). How can I give permission to your plugin / database ?

Ty

![image](https://user-images.githubusercontent.com/115706788/202176093-50ab1f51-1f34-4f80-970e-45d0b7f73cec.png)

### How To Reproduce

Put plugin in /plugin
Launch

### Plugin Version

1.16.0

### Minecraft Server

Other (please indicate in next input)

### Custom minecraft server

Mohist

### What version of minecraft are you running?

1.16.5

### Relevant log output

```shell
[13:00:16] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling MarketPlace v1.6.0 (Is it up to date?)
java.sql.SQLException: Access denied for user 'minecraft'@'localhost' (using password: NO)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323) ~[mysql-connector-java-5.1.49.jar:5.1.49]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:228) ~[java.sql:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.Database$Companion$connect$10.invoke(Database.kt:206) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.Database$Companion$connect$10.invoke(Database.kt:206) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:127) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:128) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:69) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:68) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:75) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.vendors.VendorDialect.tableExists(Default.kt:685) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.QueriesKt.exists(Queries.kt:236) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:101) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:245) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.SchemaUtils.create$default(SchemaUtils.kt:243) ~[?:?]
	at fr.fabienhebuterne.marketplace.MarketPlace$onEnable$1.invoke(MarketPlace.kt:116) ~[?:?]
	at fr.fabienhebuterne.marketplace.MarketPlace$onEnable$1.invoke(MarketPlace.kt:115) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:189) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132) ~[?:?]
	at fr.fabienhebuterne.marketplace.libs.org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:131) ~[?:?]
	at fr.fabienhebuterne.marketplace.MarketPlace.onEnable(MarketPlace.kt:115) ~[?:?]
	at fr.fabienhebuterne.marketplace.MarketPlaceLoader.onEnable(MarketPlaceLoader.kt:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[forge:7e29f765-296df566-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:413) ~[forge:7e29f765-296df566-9fb885e8]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:429) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:349) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:221) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by fhebuterne** [comment]
hi @Felix-Jonathan, this is not an issue, it seem you don't have configured DB information, by default MarketPlace use MYSQL database to work, but if you don't have any mysql db, please use SQLITE in config.json by updating type field.
