### ISSUE TITLE
Error initializing the plugin

### ISSUE THREAD

**Issue by daviddelamo** [fhebuterne/MarketPlace#8]
### Bug Description

I'm using CrafBukkit version 3077-Spigot-9fb885e-cc21bae (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) and when I try to start the server with the plugin in place the server throwns an error.

### How To Reproduce

1. Copy the plugin in the plugins folder
2. Start the server

### Expected behavior

The server should start with the plugin enabled

### Plugin Version

1.2.2

### Minecraft Server

Spigot

### Custom minecraft server

No

### What version of minecraft are you running?

1.16.5

### Relevant log output

```shell
`[08:09:55] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[08:09:55] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:09:55] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:09:55] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:09:55] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[08:09:55] [Server thread/WARN]:        at fr.fabienhebuterne.marketplace.utils.CustomClassloader.instantiatePlugin(CustomClassloader.kt:65)
[08:09:55] [Server thread/WARN]:        at fr.fabienhebuterne.marketplace.MarketPlaceLoader.<init>(MarketPlaceLoader.kt:46)
[08:09:55] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:09:55] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:09:55] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:09:55] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[08:09:55] [Server thread/WARN]:        at java.lang.Class.newInstance(Class.java:442)
[08:09:55] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79)
[08:09:55] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145)
[08:09:55] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394)
[08:09:55] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301)
[08:09:55] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:381)
[08:09:55] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:224)
[08:09:55] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928)
[08:09:55] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
[08:09:55] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[08:09:55] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException
[08:09:55] [Server thread/WARN]:        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
[08:09:55] [Server thread/WARN]:        at org.objectweb.asm.commons.ClassRemapper.<init>(ClassRemapper.java:61)
[08:09:55] [Server thread/WARN]:        at org.objectweb.asm.commons.ClassRemapper.<init>(ClassRemapper.java:56)
[08:09:55] [Server thread/WARN]:        at me.lucko.jarrelocator.JarRelocator$RelocatingClassVisitor.<init>(JarRelocator.java:190)
[08:09:55] [Server thread/WARN]:        at me.lucko.jarrelocator.JarRelocator$RelocatingClassVisitor.<init>(JarRelocator.java:186)
[08:09:55] [Server thread/WARN]:        at me.lucko.jarrelocator.JarRelocator.addRelocatedClass(JarRelocator.java:157)
[08:09:55] [Server thread/WARN]:        at me.lucko.jarrelocator.JarRelocator.run(JarRelocator.java:115)
[08:09:55] [Server thread/WARN]:        at fr.fabienhebuterne.marketplace.utils.Dependency.loadDependencies(Dependency.kt:66)
[08:09:55] [Server thread/WARN]:        at fr.fabienhebuterne.marketplace.MarketPlace.<init>(MarketPlace.kt:83)
[08:09:55] [Server thread/WARN]:        ... 20 more
[08:09:55] [Server thread/ERROR]: Could not load 'plugins/MarketPlace-1.2.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: No public constructor
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:81) ~[spigot.jar:3077-Spigot-9fb885e-cc21bae]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot.jar:3077-Spigot-9fb885e-cc21bae]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot.jar:3077-Spigot-9fb885e-cc21bae]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot.jar:3077-Spigot-9fb885e-cc21bae]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:381) ~[spigot.jar:3077-Spigot-9fb885e-cc21bae]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:224) ~[spigot.jar:3077-Spigot-9fb885e-cc21bae]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot.jar:3077-Spigot-9fb885e-cc21bae]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3077-Spigot-9fb885e-cc21bae]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.IllegalAccessException: Unable to create bootstrap plugin instance
        at fr.fabienhebuterne.marketplace.utils.CustomClassloader.instantiatePlugin(CustomClassloader.kt:68) ~[?:?]
        at fr.fabienhebuterne.marketplace.MarketPlaceLoader.<init>(MarketPlaceLoader.kt:46) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_292]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_292]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_292]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_292]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_292]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[spigot.jar:3077-Spigot-9fb885e-cc21bae]
        ... 8 more`
```

**Comment by fhebuterne** [comment]
Hi,

Thanks for report, did you have dependencies has been downloaded on first time ?

Usually, first time you have this in your logs :

```
[23:13:02] [Server thread/INFO]: Download kotlin-stdlib-1.4.31 dependency...
[23:13:02] [Server thread/INFO]: Download kotlin-stdlib-jdk8-1.4.31 dependency...
[23:13:02] [Server thread/INFO]: Download kotlin-reflect-1.4.31 dependency...
[23:13:03] [Server thread/INFO]: Download mysql-connector-java-8.0.23 dependency...
[23:13:03] [Server thread/INFO]: Download exposed-jdbc-0.32.1 dependency...
[23:13:04] [Server thread/INFO]: Download exposed-dao-0.32.1 dependency...
[23:13:04] [Server thread/INFO]: Download exposed-core-0.32.1 dependency...
[23:13:04] [Server thread/INFO]: Download kotlinx-serialization-runtime-1.0-M1-1.4.0-rc dependency...
[23:13:04] [Server thread/INFO]: Download kodein-di-jvm-7.3.1 dependency...
[23:13:04] [Server thread/INFO]: Download kodein-di-7.3.1 dependency...
[23:13:04] [Server thread/INFO]: Relocated kotlin-stdlib-1.4.31 dependency...
[23:13:05] [Server thread/INFO]: Relocated kotlin-stdlib-jdk8-1.4.31 dependency...
[23:13:05] [Server thread/INFO]: Relocated kotlin-reflect-1.4.31 dependency...
[23:13:05] [Server thread/INFO]: Relocated mysql-connector-java-8.0.23 dependency...
[23:13:06] [Server thread/INFO]: Relocated exposed-jdbc-0.32.1 dependency...
[23:13:06] [Server thread/INFO]: Relocated exposed-dao-0.32.1 dependency...
[23:13:06] [Server thread/INFO]: Relocated exposed-core-0.32.1 dependency...
[23:13:06] [Server thread/INFO]: Relocated kotlinx-serialization-runtime-1.0-M1-1.4.0-rc dependency...
[23:13:06] [Server thread/INFO]: Relocated kodein-di-jvm-7.3.1 dependency...
[23:13:06] [Server thread/INFO]: Relocated kodein-di-7.3.1 dependency...
```
With libs folder in MarketPlace plugin folder. Is it there ?

I don't reproduce your bug with spigot 1.16.5.

**Comment by daviddelamo** [comment]
I don't see anything in the logs, but the MarketPlace folder exists in the plugins directory and has this contents:

`   4 drwxr-xr-x 3 pufferpanel pufferpanel    4096 Aug 11 07:00 ..
   4 -rw-r--r-- 1 pufferpanel pufferpanel    1125 Aug 11 07:53 kotlin-stdlib-jdk8-1.4.31-relocated.jar
  16 -rw-r--r-- 1 pufferpanel pufferpanel   16220 Aug 11 07:53 kotlin-stdlib-jdk8-1.4.31.jar
1460 -rw-r--r-- 1 pufferpanel pufferpanel 1495020 Aug 11 07:53 kotlin-stdlib-1.4.31.jar
2908 -rw-r--r-- 1 pufferpanel pufferpanel 2974474 Aug 11 07:53 kotlin-reflect-1.4.31.jar
2360 -rw-r--r-- 1 pufferpanel pufferpanel 2415211 Aug 11 07:53 mysql-connector-java-8.0.23.jar
  56 -rw-r--r-- 1 pufferpanel pufferpanel   55132 Aug 11 07:53 exposed-jdbc-0.32.1.jar
 168 -rw-r--r-- 1 pufferpanel pufferpanel  171346 Aug 11 07:53 exposed-dao-0.32.1.jar
 920 -rw-r--r-- 1 pufferpanel pufferpanel  940211 Aug 11 07:53 exposed-core-0.32.1.jar
 520 -rw-r--r-- 1 pufferpanel pufferpanel  531212 Aug 11 07:53 kotlinx-serialization-runtime-1.0-M1-1.4.0-rc.jar
   4 -rw-r--r-- 1 pufferpanel pufferpanel     654 Aug 11 07:53 kotlin-stdlib-1.4.31-relocated.jar
 624 -rw-r--r-- 1 pufferpanel pufferpanel  636012 Aug 11 07:53 kodein-di-jvm-7.3.1.jar
  52 -rw-r--r-- 1 pufferpanel pufferpanel   52051 Aug 11 07:53 kodein-di-7.3.1.jar
  12 -rw-r--r-- 1 pufferpanel pufferpanel   10469 Aug 11 08:00 kotlin-reflect-1.4.31-relocated.jar
  36 -rw-r--r-- 1 pufferpanel pufferpanel   32879 Sep  2 19:11 mysql-connector-java-8.0.23-relocated.jar
   4 -rw-r--r-- 1 pufferpanel pufferpanel    1155 Oct  1 13:47 exposed-jdbc-0.32.1-relocated.jar
   4 drwxr-xr-x 2 pufferpanel pufferpanel    4096 Oct  3 08:09 .
   4 -rw-r--r-- 1 pufferpanel pufferpanel     809 Oct  3 08:09 exposed-dao-0.32.1-relocated.jar`

Thanks for your quick answer :)

**Comment by fhebuterne** [comment]
@daviddelamo Hmm, strange but i see it missing some dependencies in your folder.

Could you download this [libs.zip](https://github.com/fhebuterne/MarketPlace/files/7280577/libs.zip) and extract it and replace all libs existing please ?

Did you have any others plugins, and if yes could you give me the list please (maybe a conflit but i'm not sure) ?

**Comment by daviddelamo** [comment]
Hey, thanks for the libs, now the plugin loaded correctly. I only need to configure it properly now :D
